#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE is not set"
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "File $PYFILE does not exist"
    exit 2
fi

OUTPUT_FILE="${PYFILE}c"

python3 -c "import py_compile; py_compile.compile('$PYFILE', cfile='$OUTPUT_FILE')"

echo "Compiling $PYFILE ..."
echo "Output file is $OUTPUT_FILE"

